default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: portfoliochloe_development
  username: <%= ENV['PG_USERNAME'] %>  # Remplacer par votre utilisateur PostgreSQL si nécessaire
  password: <%= ENV['PG_PASSWORD'] %>  # Remplacer par votre mot de passe PostgreSQL si nécessaire
  host: localhost  # Si vous utilisez PostgreSQL localement

test:
  <<: *default
  database: portfoliochloe_test
  username: <%= ENV['PG_USERNAME'] %>
  password: <%= ENV['PG_PASSWORD'] %>
  host: localhost

production:
  <<: *default
  database: <%= ENV['DATABASE_URL'] %>  # Heroku ou autre service de production
  username: <%= ENV['PG_USERNAME'] %>
  password: <%= ENV['PG_PASSWORD'] %>
  host: localhost
